# Generated by Django 4.2.1 on 2023-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default='a', max_length=255, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='clearance_lvl',
            field=models.CharField(default='Level 1', max_length=255, verbose_name='Clearance Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='abebe', max_length=255, verbose_name='Middle Name'),
            preserve_default=False,
        ),
    ]
