# Generated by Django 4.2.1 on 2023-05-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('target', '0003_alter_target_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building_name', models.CharField(max_length=255, verbose_name='Building Name')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_time', models.DateTimeField(max_length=255, verbose_name='REC TIME')),
                ('facePicLocation', models.ImageField(default='TargetPic/None/No0img.jpg', max_length=255, upload_to='TargetPic/', verbose_name='Face Image')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fr.camera', verbose_name='Camera')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target.target', verbose_name='Target')),
            ],
        ),
    ]
