# Generated by Django 4.2.1 on 2023-05-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0002_alter_alert_facepiclocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='street',
        ),
        migrations.AddField(
            model_name='camera',
            name='sub_city',
            field=models.CharField(default='KK', max_length=255, verbose_name='Sub City'),
            preserve_default=False,
        ),
    ]
